In [1]:
import pandas as pd
claims_data = pd.read_csv('Test_Claims_Data.csv')
revenue_data = pd.read_csv('Test_Revenue_Data.csv')
# in_sample = pd.read_csv('DE1_Inpatient_Sample.csv',nrows=100)
claims_data['Service_Date'] = pd.to_datetime(claims_data['Service_Date'].astype(str), format='%Y%m%d').dt.strftime('%d-%m-%Y')
claims_data.Service_Date.dtype,revenue_data.Service_Date.dtype

/tmp/ipykernel_7628/3756385536.py:2: DtypeWarning: Columns (2,113,114,228) have mixed types. Specify dtype option on import or set low_memory=False.
  claims_data = pd.read_csv('Test_Claims_Data.csv')
/tmp/ipykernel_7628/3756385536.py:3: DtypeWarning: Columns (7,14) have mixed types. Specify dtype option on import or set low_memory=False.
  revenue_data = pd.read_csv('Test_Revenue_Data.csv')

(dtype('O'), dtype('O'))

In [3]:
max(revenue_data['Line_Serial'])

52

In [30]:
claims_data[
    (claims_data['Billed_Subscriber_ID']==100023222)&
    (claims_data['Patient_Account_Number']==273) &
    (claims_data['Service_Date']=='12-01-2019')][
        [
        'Billed_Subscriber_ID',
        'Patient_Account_Number',
        'Service_Date',
        'ICD_DGNS_CD2','ICD_DGNS_CD3','ICD_DGNS_CD4','ICD_DGNS_CD5','ICD_DGNS_CD6','ICD_DGNS_CD7','ICD_DGNS_CD8','ICD_DGNS_CD9','ICD_DGNS_CD10',
        'ICD_DGNS_CD11','ICD_DGNS_CD12',
        # 'ICD_DGNS_CD13','ICD_DGNS_CD14','ICD_DGNS_CD15','ICD_DGNS_CD16','ICD_DGNS_CD17','ICD_DGNS_CD18','ICD_DGNS_CD19',
        'ICD_PRCDR_CD1'
        # ,'ICD_PRCDR_CD2','ICD_PRCDR_CD3','ICD_PRCDR_CD4','ICD_PRCDR_CD5','ICD_PRCDR_CD6','ICD_PRCDR_CD7','ICD_PRCDR_CD8','ICD_PRCDR_CD9'
        ]
]

,Billed_Subscriber_ID,Patient_Account_Number,Service_Date,ICD_DGNS_CD2,ICD_DGNS_CD3,ICD_DGNS_CD4,ICD_DGNS_CD5,ICD_DGNS_CD6,ICD_DGNS_CD7,ICD_DGNS_CD8,ICD_DGNS_CD9,ICD_DGNS_CD10,ICD_DGNS_CD11,ICD_DGNS_CD12,ICD_PRCDR_CD1
0,100023222,273,12-01-2019,N390,G9340,R0902,I10,I2510,I350,G309,F0280,J449,I440,Z8673,4A033R1

In [32]:
revenue_data[
    (revenue_data['Billed_Subscriber_ID']==100023222)&
    (revenue_data['Patient_Account_Number']==273) &
    (revenue_data['Service_Date']=='12-01-2019')][
        [
    'Billed_Subscriber_ID',
    'Patient_Account_Number',
    'Service_Date',
    'Line_Revenue_Code',
    'Line_Procedure_Code',
    'Line_Procedure_Modifier_1',
    'REV_NCVR',
    'REVDEDCD',
    'Line_Amount_Total'
    ]
]
    # 'ICD_PRCDR_CD1','ICD_PRCDR_CD2','ICD_PRCDR_CD3','ICD_PRCDR_CD4','ICD_PRCDR_CD5','ICD_PRCDR_CD6','ICD_PRCDR_CD7','ICD_PRCDR_CD8','ICD_PRCDR_CD9']]

,Billed_Subscriber_ID,Patient_Account_Number,Service_Date,Line_Revenue_Code,Line_Procedure_Code,Line_Procedure_Modifier_1,REV_NCVR,REVDEDCD,Line_Amount_Total
24,100023222,273,12-01-2019,214,NaN,NaN,0.0,NaN,12000.000000
25,100023222,273,12-01-2019,250,NaN,NaN,0.0,NaN,7679.189941
26,100023222,273,12-01-2019,270,NaN,NaN,0.0,NaN,2596.000000
27,100023222,273,12-01-2019,272,NaN,NaN,0.0,NaN,50.000000
28,100023222,273,12-01-2019,300,NaN,NaN,0.0,NaN,4109.000000
29,100023222,273,12-01-2019,301,NaN,NaN,0.0,NaN,2070.000000
30,100023222,273,12-01-2019,305,NaN,NaN,0.0,NaN,1038.000000
31,100023222,273,12-01-2019,306,NaN,NaN,0.0,NaN,917.000000
32,100023222,273,12-01-2019,307,NaN,NaN,0.0,NaN,113.000000
33,100023222,273,12-01-2019,324,NaN,NaN,0.0,NaN,238.000000
34,100023222,273,12-01-2019,351,NaN,NaN,0.0,NaN,2256.000000
35,100023222,273,12-01-2019,440,NaN,NaN,0.0,NaN,1306.000000
36,100023222,273,12-01-2019,450,NaN,NaN,0.0,NaN,2493.000000
37,100023222,273,12-01-2019,483,NaN,NaN,0.0,NaN,1890.000000
38,100023222,273,12-01-2019,730,NaN,NaN,0.0,NaN,630.000000
39,100023222,273,12-01-2019,1,NaN,NaN,0.0,NaN,39385.191410

In [31]:
for c in revenue_data.columns:
    print(c)

Billed_Subscriber_ID
Patient_Account_Number
Line_Serial
Service_Date
Facility_Type_Code
Line_Revenue_Code
Line_Procedure_Code
Line_Procedure_Modifier_1
Line_Procedure_Modifier_2
Line_Procedure_Modifier_3
Line_Units
REV_RATE
Line_Amount_Total
REV_NCVR
REVDEDCD
APCHIPPS
REV_CNTR_RNDRNG_PHYSN_UPIN
Rendering_Provider_ID
REV_CNTR_RNDRNG_PHYSN_SPCLTY_CD
NDC_NumberInvestigational_Device_Exemption_ID
REV_CNTR_PRCNG_IND_CD
THRPY_CAP_IND_CD1
THRPY_CAP_IND_CD2

In [210]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.9.0-py2.py3-none-any.whl.metadata (20 kB)
Collecting scipy<1.14,>=1.4.1 (from ydata-profiling)
  Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 536.6 kB/s eta 0:00:00 0:00:01
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ydata-profiling) (2.2.2)
Collecting matplotlib<3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pydantic>=2 (from ydata-profiling)
  Downloading pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.2/125.2 kB 1.2 MB/s eta 0:00:0000:01
Collecting PyYAML<6.1,>=5.0.0 (from ydata-profiling)
  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting jinja2<3.2,>=2.11.1 (from ydata-profiling)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting visions<0.7.7,>=0.7.5 (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling)
  Downloading visions-0.7.6-py3-none-any.whl.metadata (11 kB)
Collecting numpy<2,>=1.16.0 (from ydata-profiling)
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting requests<3,>=2.24.0 (from ydata-profiling)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm<5,>=4.48.2 (from ydata-profiling)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting seaborn<0.14,>=0.10.1 (from ydata-profiling)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting typeguard<5,>=3 (from ydata-profiling)
  Downloading typeguard-4.3.0-py3-none-any.whl.metadata (3.7 kB)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting wordcloud>=1.9.1 (from ydata-profiling)
  Downloading wordcloud-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.8.1-py3-none-any.whl.metadata (15 kB)
Collecting numba<1,>=0.56.0 (from ydata-profiling)
  Downloading numba-0.60.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Downloading pywavelets-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting pillow (from imagehash==4.3.1->ydata-profiling)
  Downloading pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Collecting MarkupSafe>=2.0 (from jinja2<3.2,>=2.11.1->ydata-profiling)
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting contourpy>=1.0.1 (from matplotlib<3.10,>=3.5->ydata-profiling)
  Downloading contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib<3.10,>=3.5->ydata-profiling)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib<3.10,>=3.5->ydata-profiling)
  Downloading fonttools-4.53.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 1.7 MB/s eta 0:00:00a 0:00:01
Collecting kiwisolver>=1.3.1 (from matplotlib<3.10,>=3.5->ydata-profiling)
  Downloading kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (24.1)
Collecting pyparsing>=2.3.1 (from matplotlib<3.10,>=3.5->ydata-profiling)
  Downloading pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba<1,>=0.56.0->ydata-profiling)
  Downloading llvmlite-0.43.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: pytz>=2020.1 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Collecting joblib>=0.14.1 (from phik<0.13,>=0.11.1->ydata-profiling)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting annotated-types>=0.4.0 (from pydantic>=2->ydata-profiling)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.20.1 (from pydantic>=2->ydata-profiling)
  Downloading pydantic_core-2.20.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.24.0->ydata-profiling)
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.24.0->ydata-profiling)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.24.0->ydata-profiling)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.24.0->ydata-profiling)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-0.5.6-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting attrs>=19.3.0 (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting networkx>=2.4 (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling)
  Downloading networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
WARNING: visions 0.7.6 does not provide the extra 'type-image-path'
Requirement already satisfied: six in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata-profiling) (1.16.0)
Downloading ydata_profiling-4.9.0-py2.py3-none-any.whl (356 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 356.2/356.2 kB 3.7 MB/s eta 0:00:00:00:01
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 2.4 MB/s eta 0:00:00ta 0:00:01
Downloading dacite-1.8.1-py3-none-any.whl (14 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading matplotlib-3.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 5.0 MB/s eta 0:00:0000:0100:01m
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.60.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 5.7 MB/s eta 0:00:0000:0100:01
Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Downloading phik-0.12.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (686 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 3.8 MB/s eta 0:00:0000:0100:01
Downloading pydantic-2.8.2-py3-none-any.whl (423 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.9/423.9 kB 3.4 MB/s eta 0:00:0000:0100:01
Downloading pydantic_core-2.20.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.2 MB/s eta 0:00:0000:0100:01m
Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 4.4 MB/s eta 0:00:0000:0100:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 2.1 MB/s eta 0:00:00a 0:00:01
Downloading statsmodels-0.14.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 5.5 MB/s eta 0:00:0000:0100:01
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Downloading typeguard-4.3.0-py3-none-any.whl (35 kB)
Downloading visions-0.7.6-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 838.4 kB/s eta 0:00:000:01
Downloading wordcloud-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.1/511.1 kB 2.5 MB/s eta 0:00:0000:0100:01
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Downloading contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (305 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 305.2/305.2 kB 2.0 MB/s eta 0:00:00a 0:00:01
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.53.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 5.3 MB/s eta 0:00:0000:0100:01
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.3 MB/s eta 0:00:0000:0100:01
Downloading llvmlite-0.43.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 4.5 MB/s eta 0:00:0000:0100:01
Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Downloading networkx-3.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.4 MB/s eta 0:00:0000:0100:01
Downloading patsy-0.5.6-py2.py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 1.8 MB/s eta 0:00:00a 0:00:01
Downloading pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 5.7 MB/s eta 0:00:0000:0100:01
Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 1.1 MB/s eta 0:00:00:00:01
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Downloading pywavelets-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 4.7 MB/s eta 0:00:0000:0100:01m
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (pyproject.toml) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27083 sha256=d776b6ec70f496c647ae606488d47ea8d971c1856fa177481fe01902400e1887
  Stored in directory: /home/rana/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
Installing collected packages: htmlmin, urllib3, typeguard, tqdm, PyYAML, pyparsing, pydantic-core, pillow, numpy, networkx, multimethod, MarkupSafe, llvmlite, kiwisolver, joblib, idna, fonttools, dacite, cycler, charset-normalizer, certifi, attrs, annotated-types, scipy, requests, PyWavelets, pydantic, patsy, numba, jinja2, contourpy, visions, statsmodels, matplotlib, imagehash, wordcloud, seaborn, phik, ydata-profiling
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.1
    Uninstalling numpy-2.0.1:
      Successfully uninstalled numpy-2.0.1
Successfully installed MarkupSafe-2.1.5 PyWavelets-1.6.0 PyYAML-6.0.1 annotated-types-0.7.0 attrs-23.2.0 certifi-2024.7.4 charset-normalizer-3.3.2 contourpy-1.2.1 cycler-0.12.1 dacite-1.8.1 fonttools-4.53.1 htmlmin-0.1.12 idna-3.7 imagehash-4.3.1 jinja2-3.1.4 joblib-1.4.2 kiwisolver-1.4.5 llvmlite-0.43.0 matplotlib-3.9.1 multimethod-1.12 networkx-3.3 numba-0.60.0 numpy-1.26.4 patsy-0.5.6 phik-0.12.4 pillow-10.4.0 pydantic-2.8.2 pydantic-core-2.20.1 pyparsing-3.1.2 requests-2.32.3 scipy-1.13.1 seaborn-0.13.2 statsmodels-0.14.2 tqdm-4.66.4 typeguard-4.3.0 urllib3-2.2.2 visions-0.7.6 wordcloud-1.9.3 ydata-profiling-4.9.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

In [214]:
!pip install --upgrade numpy

Requirement already satisfied: numpy in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (1.26.4)
Collecting numpy
  Downloading numpy-2.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 537.9 kB/s eta 0:00:00 0:00:01
Downloading numpy-2.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 5.0 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.9.0 requires numpy<2,>=1.16.0, but you have numpy 2.0.1 which is incompatible.
Successfully installed numpy-2.0.1

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

In [215]:
from ydata_profiling import ProfileReport
profile = ProfileReport(claims_data, title="Profiling Report")

In [217]:
!pip install ipywidgets

Collecting ipywidgets
  Downloading ipywidgets-8.1.3-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipywidgets) (8.26.0)
Requirement already satisfied: traitlets>=4.3.1 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.11 (from ipywidgets)
  Downloading widgetsnbextension-4.0.11-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.11 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.11-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: decorator in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)
Requirement already satisfied: stack-data in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: exceptiongroup in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.2.2)
Requirement already satisfied: typing-extensions>=4.6 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.12.2)
Requirement already satisfied: pexpect>4.3 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: six>=1.12.0 in /home/rana/.cache/pypoetry/virtualenvs/bloomvalue-BF-OEI8C-py3.10/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Downloading ipywidgets-8.1.3-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.4/139.4 kB 1.3 MB/s eta 0:00:00a 0:00:01
Downloading jupyterlab_widgets-3.0.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.4/214.4 kB 1.8 MB/s eta 0:00:00ta 0:00:01
Downloading widgetsnbextension-4.0.11-py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 7.8 MB/s eta 0:00:00:00:0100:01
Installing collected packages: widgetsnbextension, jupyterlab-widgets, ipywidgets
Successfully installed ipywidgets-8.1.3 jupyterlab-widgets-3.0.11 widgetsnbextension-4.0.11

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

In [218]:
profile.to_notebook_iframe()

Summarize dataset: 100%|██████████| 4335/4335 [16:37<00:00,  4.34it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [03:20<00:00, 200.46s/it]
Render HTML: 100%|██████████| 1/1 [03:04<00:00, 184.79s/it]

In [43]:
merged_df = claims_data.merge(revenue_data, on=['Billed_Subscriber_ID', 'Patient_Account_Number', 'Service_Date'], how='left')

In [45]:
len(merged_df), len(claims_data), len(revenue_data)

(313698, 20399, 313698)

In [172]:
claims_data[(claims_data.Billed_Subscriber_ID==100023222)]

,Billed_Subscriber_ID,Patient_Account_Number,PROVIDER,Service_Date,Claim_Filing_Indicator_Code,Facility_Type_Code,QUERY_CD,Facility_Code,TYPESRVC,Frequency_Code,...,CLM_SITE_NTRL_PYMT_CST_AMT,CLM_SITE_NTRL_PYMT_IPPS_AMT,CLM_FULL_STD_PYMT_AMT,CLM_SS_OUTLIER_STD_PYMT_AMT,CLM_NEXT_GNRTN_ACO_IND_CD1,CLM_NEXT_GNRTN_ACO_IND_CD2,CLM_NEXT_GNRTN_ACO_IND_CD3,CLM_NEXT_GNRTN_ACO_IND_CD4,CLM_NEXT_GNRTN_ACO_IND_CD5,ACO_ID_NUM
0,100023222,273,50126,12-01-2019,V,60,5,1,1,I,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
794,100023222,3671748,50126,22-05-2019,V,60,3,1,1,1,...,0,0,0,0,5.0,NaN,NaN,NaN,NaN,V239

In [62]:
revenue_data[(revenue_data.Billed_Subscriber_ID==100023222) & (revenue_data.Patient_Account_Number==273) & (revenue_data.Service_Date == "12-01-2019") & (revenue_data.Line_Revenue_Code==1)]['Line_Amount_Total']

39    39385.19141
Name: Line_Amount_Total, dtype: float64

In [208]:
sub = 493385099
pan = 10584210   
dt = '17-12-2019'

# 493385099	10584210	1	17-12-2019	
# sub = 100023222
# pan = 273
# dt = '12-01-2019'
claims_data[(claims_data.Billed_Subscriber_ID==sub) & (claims_data.Patient_Account_Number==pan) & (claims_data.Service_Date == dt)]

,Billed_Subscriber_ID,Patient_Account_Number,PROVIDER,Service_Date,Claim_Filing_Indicator_Code,Facility_Type_Code,QUERY_CD,Facility_Code,TYPESRVC,Frequency_Code,...,CLM_SITE_NTRL_PYMT_CST_AMT,CLM_SITE_NTRL_PYMT_IPPS_AMT,CLM_FULL_STD_PYMT_AMT,CLM_SS_OUTLIER_STD_PYMT_AMT,CLM_NEXT_GNRTN_ACO_IND_CD1,CLM_NEXT_GNRTN_ACO_IND_CD2,CLM_NEXT_GNRTN_ACO_IND_CD3,CLM_NEXT_GNRTN_ACO_IND_CD4,CLM_NEXT_GNRTN_ACO_IND_CD5,ACO_ID_NUM
20270,493385099,10584210,70022,17-12-2019,V,60,3,1,1,1,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [209]:
merged_df[(merged_df.Billed_Subscriber_ID==sub) & (merged_df.Patient_Account_Number==pan) & (merged_df.Service_Date == dt)][[
    'Charge_Amount','Line_Amount_Total','REV_NCVR', 'Line_Procedure_Code','ICD_DGNS_CD2','ICD_PRCDR_CD1',
    'Other_Diagnosis','CLM_POA_IND_SW2','Line_Revenue_Code','Attending_Phys._ID']]

,Charge_Amount,Line_Amount_Total,REV_NCVR,Line_Procedure_Code,ICD_DGNS_CD2,ICD_PRCDR_CD1,Other_Diagnosis,CLM_POA_IND_SW2,Line_Revenue_Code,Attending_Phys._ID
311830,575239.94,383699.468800,336275.94,NaN,G936,XW03372,C7931,Y,121,1750657458
311831,575239.94,10126.009770,0.00,NaN,G936,XW03372,C7931,Y,201,1750657458
311832,575239.94,118959.132800,71.93,NaN,G936,XW03372,C7931,Y,250,1750657458
311833,575239.94,1837.209961,748.82,NaN,G936,XW03372,C7931,Y,270,1750657458
311834,575239.94,241.360001,0.00,NaN,G936,XW03372,C7931,Y,272,1750657458
311835,575239.94,2700.000000,0.00,NaN,G936,XW03372,C7931,Y,278,1750657458
311836,575239.94,5447.000000,3452.00,NaN,G936,XW03372,C7931,Y,300,1750657458
311837,575239.94,1368.000000,799.00,NaN,G936,XW03372,C7931,Y,301,1750657458
311838,575239.94,10779.330080,219.82,NaN,G936,XW03372,C7931,Y,320,1750657458
311839,575239.94,2376.510010,0.00,NaN,G936,XW03372,C7931,Y,351,1750657458
311840,575239.94,214.759995,0.00,NaN,G936,XW03372,C7931,Y,402,1750657458
311841,575239.94,11179.500000,9870.70,NaN,G936,XW03372,C7931,Y,420,1750657458
311842,575239.94,712.140015,0.00,NaN,G936,XW03372,C7931,Y,424,1750657458
311843,575239.94,992.739990,0.00,NaN,G936,XW03372,C7931,Y,444,1750657458
311844,575239.94,3804.830078,0.00,NaN,G936,XW03372,C7931,Y,450,1750657458
311845,575239.94,1653.219971,0.00,NaN,G936,XW03372,C7931,Y,480,1750657458
311846,575239.94,3326.689941,0.00,NaN,G936,XW03372,C7931,Y,481,1750657458
311847,575239.94,2506.159912,0.00,NaN,G936,XW03372,C7931,Y,611,1750657458
311848,575239.94,200.570007,0.00,NaN,G936,XW03372,C7931,Y,730,1750657458
311849,575239.94,12234.000000,0.00,NaN,G936,XW03372,C7931,Y,761,1750657458
311850,575239.94,881.309998,0.00,NaN,G936,XW03372,C7931,Y,921,1750657458
311851,575239.94,575239.937500,351438.21,NaN,G936,XW03372,C7931,Y,1,1750657458

In [168]:
revenue_data[~revenue_data['Line_Procedure_Code'].isna()]

,Billed_Subscriber_ID,Patient_Account_Number,Line_Serial,Service_Date,Facility_Type_Code,Line_Revenue_Code,Line_Procedure_Code,Line_Procedure_Modifier_1,Line_Procedure_Modifier_2,Line_Procedure_Modifier_3,...,REV_NCVR,REVDEDCD,APCHIPPS,REV_CNTR_RNDRNG_PHYSN_UPIN,Rendering_Provider_ID,REV_CNTR_RNDRNG_PHYSN_SPCLTY_CD,NDC_NumberInvestigational_Device_Exemption_ID,REV_CNTR_PRCNG_IND_CD,THRPY_CAP_IND_CD1,THRPY_CAP_IND_CD2
2495,109612754,76051,1,04-01-2019,60,24,A0105,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
13799,455560801,459057,1,24-01-2019,60,24,A0110,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
15617,462021909,521968,1,29-01-2019,60,24,D2004,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
17617,467782571,580138,1,24-01-2019,60,24,C0704,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
17914,468987786,591954,1,05-01-2019,60,24,A0602,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310971,492113268,10569597,1,23-12-2019,60,24,C0303,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
312709,496921606,10623946,1,18-12-2019,60,24,C0304,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
313217,498560406,10642624,1,24-12-2019,60,24,A0103,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
313657,499973125,10658356,1,20-12-2019,60,24,D0703,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN
313671,499973125,10658357,1,30-12-2019,60,24,D0703,NaN,NaN,NaN,...,0.0,NaN,0,NaN,NaN,NaN,NaN,A,NaN,NaN

In [69]:
revenue_data[(revenue_data.Billed_Subscriber_ID==sub) & (revenue_data.Patient_Account_Number==pan) & (revenue_data.Service_Date == dt) & (revenue_data.Line_Revenue_Code==1)]['Line_Amount_Total']

313584    108622.8984
Name: Line_Amount_Total, dtype: float64

In [73]:
rev_1_data = revenue_data[revenue_data.Line_Revenue_Code==1]
len(rev_1_data), len(claims_data)

(20399, 20399)

In [75]:
merged_rev_1_df = claims_data.merge(rev_1_data, on=['Billed_Subscriber_ID', 'Patient_Account_Number', 'Service_Date'], how='left')
len(merged_rev_1_df)

20399

In [79]:
merged_rev_1_df['diff']=merged_rev_1_df['Charge_Amount'] - merged_rev_1_df['Line_Amount_Total']

In [83]:
min(merged_rev_1_df['diff']), max(merged_rev_1_df['diff'])

(-0.10999999986961484, 0.060000000055879354)

In [122]:
claims_data.columns()

AttributeError: 'DataFrame' object has no attribute 'Attending_Phys'

In [155]:
claims_data[['Other_Diagnosis','ICD_DGNS_CD2','CLM_POA_IND_SW2','ICD_DGNS_CD3','CLM_POA_IND_SW3','ICD_DGNS_CD4', 'ICD_DGNS_CD15']]

,Other_Diagnosis,ICD_DGNS_CD2,CLM_POA_IND_SW2,ICD_DGNS_CD3,CLM_POA_IND_SW3,ICD_DGNS_CD4,ICD_DGNS_CD15
0,A4102,N390,Y,G9340,Y,R0902,NaN
1,A419,J690,Y,R532,Y,E440,E8809
2,I9589,E43,Y,G92,Y,Z681,Z7902
3,A419,J189,Y,J9601,Y,I5033,K219
4,A419,E43,Y,R532,Y,J690,N200
...,...,...,...,...,...,...,...
20394,S066X9A,N179,N,E7800,Y,I10,F17200
20395,E11610,I82502,Y,E1122,Y,N189,G8929
20396,S065X9A,I421,Y,I472,N,N390,I081
20397,A419,N186,Y,R6521,N,R571,R188
20398,I130,I5023,Y,N179,Y,I739,Z8673

In [148]:
claims_data.ICD_DGNS_CD2.value_counts()

ICD_DGNS_CD2
N186       1053
N179        746
J9601       614
E43         609
I5033       554
           ...
Z7902         1
S32401A       1
C661          1
K7689         1
Z1619         1
Name: count, Length: 1960, dtype: int64

In [177]:
valc1 = []
for c in claims_data.columns:
    if len(claims_data[c].value_counts().values)>2:
        valc1.append(c)
valc1

['Billed_Subscriber_ID',
 'Patient_Account_Number',
 'PROVIDER',
 'Service_Date',
 'QUERY_CD',
 'Frequency_Code',
 'NOPAY_CD',
 'Paid_Amount',
 'PRPAYAMT',
 'PRPAY_CD',
 'ACTIONCD',
 'Attending_Phys._ID',
 'Operating_Phys._ID',
 'Other_Operating_Phys._ID',
 'Patient_Status_Code',
 'Charge_Amount',
 'Admission_Date',
 'Admission_Type_Code',
 'Admission_Source_Code',
 'PTNTSTUS',
 'PER_DIEM',
 'Line_Adj_Patient',
 'COIN_AMT',
 'NCCHGAMT',
 'MIA_Claim_PPS_Capital_Amount',
 'MIA_PPS_Capital_FSP_DRG_Amount',
 'MIA_Claim_PPS_Capital_Outlier_Amount',
 'MIA_Claim_Disproportionate_Share_Amount',
 'MIA_PPS_Capital_IME_Amount',
 'DRG_Weight',
 'MIA_Covered_Days',
 'CoInsured_Days',
 'LRD_USE',
 'Non-Covered_Days',
 'NCOVFROM',
 'NCOVTHRU',
 'EXHST_DT',
 'Discharge_Hour',
 'DRG_Code',
 'MIA_PPS_Operating_Outlier_Amount',
 'Admitting_Diagnosis',
 'Principal_Diagnosis',
 'Other_Diagnosis',
 'CLM_POA_IND_SW1',
 'ICD_DGNS_CD2',
 'CLM_POA_IND_SW2',
 'ICD_DGNS_CD3',
 'CLM_POA_IND_SW3',
 'ICD_DGNS_CD4',
 'CLM_POA_IND_SW4',
 'ICD_DGNS_CD5',
 'CLM_POA_IND_SW5',
 'ICD_DGNS_CD6',
 'CLM_POA_IND_SW6',
 'ICD_DGNS_CD7',
 'CLM_POA_IND_SW7',
 'ICD_DGNS_CD8',
 'CLM_POA_IND_SW8',
 'ICD_DGNS_CD9',
 'CLM_POA_IND_SW9',
 'ICD_DGNS_CD10',
 'CLM_POA_IND_SW10',
 'ICD_DGNS_CD11',
 'CLM_POA_IND_SW11',
 'ICD_DGNS_CD12',
 'CLM_POA_IND_SW12',
 'ICD_DGNS_CD13',
 'CLM_POA_IND_SW13',
 'ICD_DGNS_CD14',
 'CLM_POA_IND_SW14',
 'ICD_DGNS_CD15',
 'CLM_POA_IND_SW15',
 'ICD_DGNS_CD16',
 'CLM_POA_IND_SW16',
 'ICD_DGNS_CD17',
 'CLM_POA_IND_SW17',
 'ICD_DGNS_CD18',
 'CLM_POA_IND_SW18',
 'ICD_DGNS_CD19',
 'CLM_POA_IND_SW19',
 'ICD_DGNS_CD20',
 'CLM_POA_IND_SW20',
 'ICD_DGNS_CD21',
 'CLM_POA_IND_SW21',
 'ICD_DGNS_CD22',
 'CLM_POA_IND_SW22',
 'ICD_DGNS_CD23',
 'CLM_POA_IND_SW23',
 'ICD_DGNS_CD24',
 'CLM_POA_IND_SW24',
 'ICD_DGNS_CD25',
 'CLM_POA_IND_SW25',
 'FST_DGNS_E_CD',
 'ICD_DGNS_E_CD1',
 'ICD_PRCDR_CD1',
 'PRCDR_DT1',
 'ICD_PRCDR_CD2',
 'PRCDR_DT2',
 'ICD_PRCDR_CD3',
 'PRCDR_DT3',
 'ICD_PRCDR_CD4',
 'PRCDR_DT4',
 'ICD_PRCDR_CD5',
 'PRCDR_DT5',
 'ICD_PRCDR_CD6',
 'PRCDR_DT6',
 'ICD_PRCDR_CD7',
 'PRCDR_DT7',
 'ICD_PRCDR_CD8',
 'PRCDR_DT8',
 'ICD_PRCDR_CD9',
 'PRCDR_DT9',
 'ICD_PRCDR_CD10',
 'PRCDR_DT10',
 'ICD_PRCDR_CD11',
 'PRCDR_DT11',
 'ICD_PRCDR_CD12',
 'PRCDR_DT12',
 'ICD_PRCDR_CD13',
 'PRCDR_DT13',
 'ICD_PRCDR_CD14',
 'PRCDR_DT14',
 'ICD_PRCDR_CD15',
 'PRCDR_DT15',
 'ICD_PRCDR_CD16',
 'PRCDR_DT16',
 'ICD_PRCDR_CD17',
 'PRCDR_DT17',
 'ICD_PRCDR_CD18',
 'PRCDR_DT18',
 'ICD_PRCDR_CD19',
 'PRCDR_DT19',
 'ICD_PRCDR_CD20',
 'PRCDR_DT20',
 'ICD_PRCDR_CD21',
 'PRCDR_DT21',
 'ICD_PRCDR_CD22',
 'PRCDR_DT22',
 'ICD_PRCDR_CD23',
 'PRCDR_DT23',
 'ICD_PRCDR_CD24',
 'PRCDR_DT24',
 'ICD_PRCDR_CD25',
 'PRCDR_DT25',
 'Subscriber_DOB',
 'RACE_CD',
 'CNTY_CD',
 'Subscriber_State',
 'CWF_BENE_MDCR_STUS_CD',
 'CLM_PRCR_RTRN_CD',
 'CLM_BASE_OPRTG_DRG_AMT',
 'CLM_VBP_ADJSTMT_PCT',
 'CLM_HRR_ADJSTMT_PCT',
 'CLM_UNCOMPD_CARE_PMT_AMT',
 'CLM_VBP_ADJSTMT_PMT_AMT',
 'CLM_HRR_ADJSTMT_PMT_AMT',
 'PPS_STD_VAL_PYMT_AMT',
 'FINL_STD_AMT']

In [178]:
valc1 = []
for c in revenue_data.columns:
    if len(revenue_data[c].value_counts().values)>2:
        valc1.append(c)
valc1

['Billed_Subscriber_ID',
 'Patient_Account_Number',
 'Line_Serial',
 'Service_Date',
 'Line_Revenue_Code',
 'Line_Procedure_Code',
 'Line_Units',
 'REV_RATE',
 'Line_Amount_Total',
 'REV_NCVR',
 'REV_CNTR_PRCNG_IND_CD']

In [206]:
revenue_data.REV_NCVR.value_counts()

REV_NCVR
0.00          300587
4258.00          387
4311.23          340
703.00           254
198.00           205
               ...
336275.94          1
4438948.91         1
1762.62            1
355644.00          1
165965.54          1
Name: count, Length: 5971, dtype: int64

In [207]:
revenue_data[revenue_data.REV_NCVR==336275.94]

,Billed_Subscriber_ID,Patient_Account_Number,Line_Serial,Service_Date,Facility_Type_Code,Line_Revenue_Code,Line_Procedure_Code,Line_Procedure_Modifier_1,Line_Procedure_Modifier_2,Line_Procedure_Modifier_3,...,REV_NCVR,REVDEDCD,APCHIPPS,REV_CNTR_RNDRNG_PHYSN_UPIN,Rendering_Provider_ID,REV_CNTR_RNDRNG_PHYSN_SPCLTY_CD,NDC_NumberInvestigational_Device_Exemption_ID,REV_CNTR_PRCNG_IND_CD,THRPY_CAP_IND_CD1,THRPY_CAP_IND_CD2
311343,493385099,10584210,1,17-12-2019,60,121,NaN,NaN,NaN,NaN,...,336275.94,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
revenue_data[['Facility_Type_Code','Line_Revenue_Code','Line_Procedure_Code']]

        Facility_Type_Code  Line_Revenue_Code Line_Procedure_Code
0                       60                121                 NaN
1                       60                250                 NaN
2                       60                260                 NaN
3                       60                270                 NaN
4                       60                300                 NaN
...                    ...                ...                 ...
313693                  60                410                 NaN
313694                  60                480                 NaN
313695                  60                730                 NaN
313696                  60                921                 NaN
313697                  60                  1                 NaN

[313698 rows x 3 columns]

In [110]:
revenue_data['Line_Amount_Total'].value_counts()

Line_Amount_Total
703.000000      7239
712.140015      6176
2609.000000     4391
2642.919922     3723
198.000000      3662
                ...
358.200012         1
3767.280029        1
33883.761720       1
56.340000          1
51570.218750       1
Name: count, Length: 75228, dtype: int64